### PR TITLE
bugfix Sweep

### PR DESCRIPTION
**Pull request by dalehenrich**
Nominate bugs that you'd like to see addressed from the [GsDevKit issues](https://github.com/GsDevKit/GsDevKit/issues) or [the older google code glassed issues](https://github.com/GsDevKit/glassdb/issues).

Nominations:
- [x] #77 from Dale
- [ ] #76 from Dale [DEFER]
- [x] #75 from Iwan (see PR #5)
- [x] #74 from Dale, [see comment-2](https://github.com/glassdb/glass/pull/3#issuecomment-139671037)
- [ ] #73 from Dale, [see comment-1](https://github.com/glassdb/glass/pull/3#issuecomment-139609664) [DEFER]
- [x] #72  from Mariano, [see comment](https://github.com/glassdb/glass/pull/3#issuecomment-139607889)
- [x] #71  from Mariano, [see comment](https://github.com/glassdb/glass/pull/3#issuecomment-139607889)
- [x] #70  from Mariano, [see comment](https://github.com/glassdb/glass/pull/3#issuecomment-139607889)
- [x] #58  from Mariano, [see comment](https://github.com/glassdb/glass/pull/3#issuecomment-139607889)
- [x] #29 from Johan [see comment](https://github.com/glassdb/glass/pull/3#issuecomment-139849472)
- [x] #20  from Mariano, [see comment](https://github.com/glassdb/glass/pull/3#issuecomment-139607889)

### CODE REVIEW

**Comment by marianopeck** [comment]
I would like to have #72 fixed, but you said another kind of better solution may be needed. The one proposed there DOES work for me.
#70 and #71 and enchacements and those are not easy to test. I have been using both in production since some time already and no problems. 
#20 should be integrated I think. Problem was with uppercase symbols and with the need of extended parser. A simple failure test that gets fixed with those changes is as simple as `self assert: '7.3470570000000004E+02' asNumber printString = '7.3470569999999998E+02'` 
#58 would be nice, but you said you should check in other Gemstones...

Those are all I've remember myself.

**Comment by dalehenrich** [comment]
Take a look at #73 and consider for inclusion

**Comment by dalehenrich** [comment]
@marianopeck ... excellent ... just what I was looking for!

**Comment by dalehenrich** [comment]
add Issue #74: class migration problem

**Comment by jbrichau** [comment]
I'm nominating https://github.com/GsDevKit/GsDevKit/issues/29 : include Grease 1.1.? into GLASS1

**Comment by IwanVosloo** [comment]
Pull request created for #75 at: https://github.com/GsDevKit/GsDevKit/pull/78

**Pull request merged**
