### PR TITLE
Fix for issue #96: Date>>asDateAndTime in GS 3.2+

### PR DESCRIPTION
**Pull request by jbrichau**
Fix for https://github.com/GsDevKit/GsDevKit/issues/96

@dalehenrich I notice there already is a Squeak package for GS 3.4 but I cannot download that version of Gemstone to make the code changes? How can I change the method as well for 3.4?

### CODE REVIEW

**Comment by jbrichau** [comment]
The simplest pull request in history probably, but it did make explore tode for real now :) Onwards...

**Comment by dalehenrich** [comment]
The easiest way would be to simply edit the `repository/Squeak.v34.package/Date.extension/instance/asDateAndTime.st` file with vi ... normally a manual edit would require a bump to the mcz version number, but since 3.4 isn't release, I'll be the only person affected ... the `mc bump` command in tODE can be used to bump the version number of a non-loaded package --- it was created just for this reason:)

**Comment by dalehenrich** [comment]
Cool:)

**Comment by jbrichau** [comment]
I'm trying to bump the version with `mc bump Squeak.v34 filetree:///Users/jbrichau/github/GsDevKit_home/shared/repos/glass/repository` but I'm getting a debugger on that one. I must misunderstand one of the arguments of the command.

**Comment by dalehenrich** [comment]
The bump needs a last argument with the commit message:

|mc bump Squeak.v34 
filetree:///Users/jbrichau/github/GsDevKit_home/shared/repos/glass/repository 
`fix iss #96`|

|My error messages may not be that good ... the  `mc` commands were some 
of the first commands created and I need to rewrite them in a newer 
style --- which includes better error messages:)
|

|Dale
|

**Comment by jbrichau** [comment]
Silly me, just noticed that I was indeed missing the commit message :) thx

**Pull request merged**
